version: '3.8'

services:
  nuxt-app:
    build: .
    ports:
      - "3000:3000" # format: host:container
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    restart: unless-stopped
